# Generated by Django 4.1.3 on 2023-07-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.TextField(max_length=100)),
                ('contact_message', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'contactmessage',
            },
        ),
    ]
