# Generated by Django 4.1.3 on 2023-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='contact_email',
            field=models.TextField(db_column='email', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='contact_message',
            field=models.TextField(db_column='message', max_length=1000),
        ),
    ]
