# Generated by Django 4.1.3 on 2023-07-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_contactmessage_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(db_column='firstname', max_length=50)),
                ('lname', models.TextField(db_column='lastname', max_length=50)),
                ('mob', models.TextField(db_column='mobile', max_length=10)),
                ('city', models.TextField(db_column='city', max_length=50)),
                ('state', models.TextField(db_column='state', max_length=50)),
                ('crtepswd', models.TextField(db_column='createdpassword', max_length=100)),
                ('pswd', models.TextField(db_column='password', max_length=100)),
            ],
            options={
                'db_table': 'customer_registration_details',
            },
        ),
        migrations.CreateModel(
            name='Registrationmember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(db_column='firstname', max_length=50)),
                ('lname', models.TextField(db_column='lastname', max_length=50)),
                ('mob', models.TextField(db_column='mobile', max_length=10)),
                ('city', models.TextField(db_column='city', max_length=50)),
                ('state', models.TextField(db_column='state', max_length=50)),
                ('busns', models.TextField(db_column='business', max_length=50)),
                ('crtepswd', models.TextField(db_column='createdpassword', max_length=100)),
                ('pswd', models.TextField(db_column='password', max_length=100)),
            ],
            options={
                'db_table': 'member_registration_details',
            },
        ),
    ]
