# Generated by Django 4.1.3 on 2023-07-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_registrationcustomer_registrationmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmember',
            name='busns',
            field=models.TextField(db_column='business', max_length=50, null=True),
        ),
    ]
