# Generated by Django 4.1.3 on 2023-07-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_registrationmember_busns'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcustomer',
            name='email',
            field=models.TextField(db_column='mail', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrationcustomer',
            name='type',
            field=models.TextField(db_column='user type', null=True),
        ),
        migrations.AddField(
            model_name='registrationmember',
            name='email',
            field=models.TextField(db_column='mail', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationcustomer',
            name='city',
            field=models.TextField(db_column='city', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationcustomer',
            name='crtepswd',
            field=models.TextField(db_column='createdpassword', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationcustomer',
            name='fname',
            field=models.TextField(db_column='firstname', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationcustomer',
            name='lname',
            field=models.TextField(db_column='lastname', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationcustomer',
            name='mob',
            field=models.TextField(db_column='mobile', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrationcustomer',
            name='pswd',
            field=models.TextField(db_column='password', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationcustomer',
            name='state',
            field=models.TextField(db_column='state', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='city',
            field=models.TextField(db_column='city', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='crtepswd',
            field=models.TextField(db_column='createdpassword', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='fname',
            field=models.TextField(db_column='firstname', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='lname',
            field=models.TextField(db_column='lastname', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='mob',
            field=models.TextField(db_column='mobile', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='pswd',
            field=models.TextField(db_column='password', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='state',
            field=models.TextField(db_column='state', max_length=50, null=True),
        ),
    ]
