# Generated by Django 4.1.3 on 2023-07-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_registrationmember_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcustomer',
            name='otp',
            field=models.TextField(db_column='otp', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='registrationcustomer',
            name='status',
            field=models.TextField(db_column='status', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registrationmember',
            name='otp',
            field=models.TextField(db_column='otp', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='registrationmember',
            name='status',
            field=models.TextField(db_column='status', max_length=10, null=True),
        ),
    ]
