# Generated by Django 4.1.3 on 2023-07-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_registrationcustomer_otp_registrationcustomer_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrationmember',
        ),
    ]
