# Generated by Django 4.1.3 on 2023-08-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_delete_registrationmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationcustomer',
            name='type',
        ),
    ]
