# Generated by Django 4.1.3 on 2023-07-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurentregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.TextField(db_column='Name', max_length=50)),
                ('res_place', models.TextField(db_column='Place', max_length=100)),
                ('res_address', models.TextField(db_column='Address', max_length=150)),
                ('res_pincode', models.TextField(db_column='Pincode', max_length=10)),
                ('res_owner_firstname', models.TextField(db_column='Owner_fname', max_length=50)),
                ('res_owner_secondname', models.TextField(db_column='Owner_lname', max_length=50)),
                ('res_owner_mail', models.TextField(db_column='mail', max_length=50)),
                ('res_owner_mobile', models.TextField(db_column='mobile', max_length=10)),
                ('res_create_password', models.TextField(db_column='created_password', max_length=50)),
                ('res_password', models.TextField(db_column='password', max_length=50)),
            ],
            options={
                'db_table': 'RestaurentRegistration',
            },
        ),
    ]
