# Generated by Django 4.1.3 on 2023-07-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurentregistration',
            table='restaurentregistration',
        ),
    ]
