# Generated by Django 4.1.3 on 2023-08-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_restaurentregistration_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotelregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(db_column='Name', max_length=50, null=True)),
                ('date_of_birth', models.DateField(db_column='dob', max_length=100, null=True)),
                ('e_mail', models.TextField(db_column='email', max_length=150, null=True)),
                ('mobile_number', models.TextField(db_column='mobilenumber', max_length=10, null=True)),
                ('gender', models.TextField(db_column='gender', max_length=10, null=True)),
                ('profile_photo', models.FileField(db_column='profile', max_length=50, null=True, upload_to='')),
                ('id_type', models.TextField(db_column='idtype', max_length=50, null=True)),
                ('id_number', models.TextField(db_column='idnumber', max_length=50, null=True)),
                ('image_of_id', models.FileField(db_column='imageofid', max_length=10, null=True, upload_to='')),
                ('second_id_type', models.TextField(db_column='secondidtype', max_length=50, null=True)),
                ('second_id_number', models.TextField(db_column='secondidnumber', max_length=50, null=True)),
                ('second_image_of_id', models.FileField(db_column='secondidimage', max_length=10, null=True, upload_to='')),
                ('nationality', models.TextField(db_column='nationality', max_length=100, null=True)),
                ('state', models.TextField(db_column='state', max_length=100, null=True)),
                ('district', models.TextField(db_column='district', max_length=100, null=True)),
                ('street_name', models.TextField(db_column='streetname', max_length=100, null=True)),
                ('post', models.TextField(db_column='post', max_length=100, null=True)),
                ('pin_code', models.TextField(db_column='pincode', max_length=100, null=True)),
                ('wapp_number', models.TextField(db_column='wappnumber', max_length=10, null=True)),
                ('photos', models.FileField(db_column='photos', max_length=50, null=True, upload_to='')),
                ('hotel_name', models.TextField(db_column='hotelname', max_length=100, null=True)),
                ('hotel_address', models.TextField(db_column='hoteladdress', max_length=200, null=True)),
                ('license_photo', models.FileField(db_column='licensephoto', max_length=50, null=True, upload_to='')),
                ('working_hours', models.TextField(db_column='workinghours', max_length=150, null=True)),
                ('username', models.TextField(db_column='username', max_length=150, null=True)),
                ('confirm_username', models.TextField(db_column='cusername', max_length=10, null=True)),
                ('password', models.TextField(db_column='password', max_length=150, null=True)),
                ('confirm_password', models.TextField(db_column='cpassword', max_length=10, null=True)),
            ],
            options={
                'db_table': 'hotelregistration',
            },
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='res_address',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='res_create_password',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='res_name',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='res_owner_firstname',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='res_owner_mail',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='res_owner_mobile',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='res_owner_secondname',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='res_password',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='res_pincode',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='res_place',
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='confirm_password',
            field=models.TextField(db_column='cpassword', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='confirm_username',
            field=models.TextField(db_column='cusername', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='date_of_birth',
            field=models.DateField(db_column='dob', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='district',
            field=models.TextField(db_column='district', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='e_mail',
            field=models.TextField(db_column='email', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='full_name',
            field=models.TextField(db_column='Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='gender',
            field=models.TextField(db_column='gender', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='id_number',
            field=models.TextField(db_column='idnumber', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='id_type',
            field=models.TextField(db_column='idtype', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='image_of_id',
            field=models.FileField(db_column='imageofid', max_length=10, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='license_photo',
            field=models.FileField(db_column='licensephoto', max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='mobile_number',
            field=models.TextField(db_column='mobilenumber', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='nationality',
            field=models.TextField(db_column='nationality', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='password',
            field=models.TextField(db_column='password', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='photos',
            field=models.FileField(db_column='photos', max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='pin_code',
            field=models.TextField(db_column='pincode', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='post',
            field=models.TextField(db_column='post', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='profile_photo',
            field=models.FileField(db_column='profile', max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='rest_address',
            field=models.TextField(db_column='restaddress', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='rest_name',
            field=models.TextField(db_column='restname', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='second_id_number',
            field=models.TextField(db_column='secondidnumber', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='second_id_type',
            field=models.TextField(db_column='secondidtype', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='second_image_of_id',
            field=models.FileField(db_column='secondidimage', max_length=10, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='state',
            field=models.TextField(db_column='state', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='street_name',
            field=models.TextField(db_column='streetname', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='username',
            field=models.TextField(db_column='username', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='wapp_number',
            field=models.TextField(db_column='wappnumber', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='working_hours',
            field=models.TextField(db_column='workinghours', max_length=150, null=True),
        ),
    ]
