# Generated by Django 4.1.3 on 2023-08-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_driverregistration_guideregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='status',
            field=models.TextField(db_column='status', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='guideregistration',
            name='status',
            field=models.TextField(db_column='status', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='status',
            field=models.TextField(db_column='status', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='photographerregistration',
            name='status',
            field=models.TextField(db_column='status', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='status',
            field=models.TextField(db_column='status', max_length=10, null=True),
        ),
    ]
