# Generated by Django 4.1.3 on 2023-08-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_driverregistration_status_guideregistration_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='confirm_username',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='district',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='license_photo',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='post',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='second_id_number',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='second_id_type',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='second_image_of_id',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='state',
        ),
        migrations.RemoveField(
            model_name='restaurentregistration',
            name='street_name',
        ),
        migrations.AddField(
            model_name='restaurentregistration',
            name='license_number',
            field=models.TextField(db_column='licensenumber', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='image_of_id',
            field=models.ImageField(db_column='imageofid', max_length=10, null=True, upload_to=''),
        ),
    ]
