from django.db import models

# Create your models here.
class Restaurentregistration(models.Model):
    full_name = models.TextField(max_length=50,db_column="Name" ,null=True)
    date_of_birth = models.DateField(max_length=100,db_column="dob",null=True )
    e_mail = models.TextField(max_length=150,db_column="email",null=True)
    mobile_number = models.TextField(max_length=10,db_column="mobilenumber",null=True)
    gender = models.TextField(max_length=10,db_column="gender",null=True)
    profile_photo = models.FileField(max_length=50,db_column="profile",null=True)
    id_type = models.TextField(max_length=50,db_column="idtype",null=True)
    id_number = models.TextField(max_length=50,db_column="idnumber",null=True)
    image_of_id = models.FileField(max_length=10,db_column="imageofid",null=True)
    wapp_number = models.TextField(max_length=10,db_column="wappnumber",null=True)
    photos = models.FileField(max_length=50,db_column="photos",null=True)
    rest_name = models.TextField(max_length=100,db_column="restname",null=True)
    rest_address= models.TextField(max_length=200,db_column="restaddress",null=True)
    license_number = models.TextField(max_length=50,db_column="licensenumber",null=True)
    working_hours = models.TextField(max_length=150,db_column="workinghours",null=True)
    username = models.TextField(max_length=150,db_column="username",null=True)
    password = models.TextField(max_length=150,db_column="password",null=True)
    confirm_password = models.TextField(max_length=10,db_column="cpassword",null=True)
    status = models.TextField(max_length=10,db_column='status',null=True)
    class Meta:
        db_table='restaurentregistration'
    
class Hotelregistration(models.Model):
    full_name = models.TextField(max_length=50,db_column="Name",null=True)
    date_of_birth = models.DateField(max_length=100,db_column="dob",null=True)
    e_mail = models.TextField(max_length=150,db_column="email",null=True)
    mobile_number = models.TextField(max_length=10,db_column="mobilenumber",null=True)
    gender = models.TextField(max_length=10,db_column="gender",null=True)
    profile_photo = models.FileField(max_length=50,db_column="profile",null=True)
    id_type = models.TextField(max_length=50,db_column="idtype",null=True)
    id_number = models.TextField(max_length=50,db_column="idnumber",null=True)
    image_of_id = models.FileField(max_length=10,db_column="imageofid",null=True)
    second_id_type = models.TextField(max_length=50,db_column="secondidtype",null=True)
    second_id_number = models.TextField(max_length=50,db_column="secondidnumber",null=True)
    second_image_of_id = models.FileField(max_length=10,db_column="secondidimage",null=True)
    nationality = models.TextField(max_length=100,db_column="nationality",null=True)
    state = models.TextField(max_length=100,db_column="state",null=True)
    district = models.TextField(max_length=100,db_column="district",null=True)
    street_name = models.TextField(max_length=100,db_column="streetname",null=True)
    post = models.TextField(max_length=100,db_column="post",null=True)
    pin_code = models.TextField(max_length=100,db_column="pincode",null=True)
    wapp_number = models.TextField(max_length=10,db_column="wappnumber",null=True)
    photos = models.FileField(max_length=50,db_column="photos",null=True)
    hotel_name = models.TextField(max_length=100,db_column="hotelname",null=True)
    hotel_address= models.TextField(max_length=200,db_column="hoteladdress",null=True)
    license_photo = models.FileField(max_length=50,db_column="licensephoto",null=True)
    working_hours = models.TextField(max_length=150,db_column="workinghours",null=True)
    username = models.TextField(max_length=150,db_column="username",null=True)
    confirm_username = models.TextField(max_length=10,db_column="cusername",null=True)
    password = models.TextField(max_length=150,db_column="password",null=True)
    confirm_password = models.TextField(max_length=10,db_column="cpassword",null=True)
    status = models.TextField(max_length=10,db_column='status',null=True)
    class Meta:
        db_table='hotelregistration'
        

class Photographerregistration(models.Model):
    full_name = models.TextField(max_length=50,db_column="Name",null=True)
    date_of_birth = models.DateField(max_length=100,db_column="dob",null=True)
    e_mail = models.TextField(max_length=150,db_column="email",null=True)
    mobile_number = models.TextField(max_length=10,db_column="mobilenumber",null=True)
    gender = models.TextField(max_length=10,db_column="gender",null=True)
    profile_photo = models.FileField(max_length=50,db_column="profile",null=True)
    id_type = models.TextField(max_length=50,db_column="idtype",null=True)
    id_number = models.TextField(max_length=50,db_column="idnumber",null=True)
    image_of_id = models.FileField(max_length=10,db_column="imageofid",null=True)
    second_id_type = models.TextField(max_length=50,db_column="secondidtype",null=True)
    second_id_number = models.TextField(max_length=50,db_column="secondidnumber",null=True)
    second_image_of_id = models.FileField(max_length=10,db_column="secondidimage",null=True)
    nationality = models.TextField(max_length=100,db_column="nationality",null=True)
    state = models.TextField(max_length=100,db_column="state",null=True)
    district = models.TextField(max_length=100,db_column="district",null=True)
    street_name = models.TextField(max_length=100,db_column="streetname",null=True)
    post = models.TextField(max_length=100,db_column="post",null=True)
    pin_code = models.TextField(max_length=100,db_column="pincode",null=True)
    wapp_number = models.TextField(max_length=10,db_column="wappnumber",null=True)
    photos = models.FileField(max_length=50,db_column="photos",null=True)
    available_place = models.TextField(max_length=100,db_column="availableplace",null=True)
    available_time= models.TextField(max_length=200,db_column="availabletime",null=True)
    studio_name = models.TextField(max_length=50,db_column="studioname",null=True)
    amount_hours = models.TextField(max_length=150,db_column="workinghours",null=True)
    username = models.TextField(max_length=150,db_column="username",null=True)
    confirm_username = models.TextField(max_length=10,db_column="cusername",null=True)
    password = models.TextField(max_length=150,db_column="password",null=True)
    confirm_password = models.TextField(max_length=10,db_column="cpassword",null=True)
    status = models.TextField(max_length=10,db_column='status',null=True)
    class Meta:
        db_table='photographerregistration'
        
class Guideregistration(models.Model):
    full_name = models.TextField(max_length=50,db_column="Name",null=True)
    date_of_birth = models.DateField(max_length=100,db_column="dob",null=True)
    e_mail = models.TextField(max_length=150,db_column="email",null=True)
    mobile_number = models.TextField(max_length=10,db_column="mobilenumber",null=True)
    gender = models.TextField(max_length=10,db_column="gender",null=True)
    profile_photo = models.FileField(max_length=50,db_column="profile",null=True)
    id_type = models.TextField(max_length=50,db_column="idtype",null=True)
    id_number = models.TextField(max_length=50,db_column="idnumber",null=True)
    image_of_id = models.FileField(max_length=10,db_column="imageofid",null=True)
    second_id_type = models.TextField(max_length=50,db_column="secondidtype",null=True)
    second_id_number = models.TextField(max_length=50,db_column="secondidnumber",null=True)
    second_image_of_id = models.FileField(max_length=10,db_column="secondidimage",null=True)
    nationality = models.TextField(max_length=100,db_column="nationality",null=True)
    state = models.TextField(max_length=100,db_column="state",null=True)
    district = models.TextField(max_length=100,db_column="district",null=True)
    street_name = models.TextField(max_length=100,db_column="streetname",null=True)
    post = models.TextField(max_length=100,db_column="post",null=True)
    pin_code = models.TextField(max_length=100,db_column="pincode",null=True)
    wapp_number = models.TextField(max_length=10,db_column="wappnumber",null=True)
    available_place = models.TextField(max_length=100,db_column="availableplace",null=True)
    available_time= models.TextField(max_length=200,db_column="availabletime",null=True)
    amount_hours = models.TextField(max_length=150,db_column="workinghours",null=True)
    username = models.TextField(max_length=150,db_column="username",null=True)
    confirm_username = models.TextField(max_length=10,db_column="cusername",null=True)
    password = models.TextField(max_length=150,db_column="password",null=True)
    confirm_password = models.TextField(max_length=10,db_column="cpassword",null=True)
    status = models.TextField(max_length=10,db_column='status',null=True)
    class Meta:
        db_table='guideregistration'    
        
class Driverregistration(models.Model):
    full_name = models.TextField(max_length=50,db_column="Name",null=True)
    date_of_birth = models.DateField(max_length=100,db_column="dob",null=True)
    e_mail = models.TextField(max_length=150,db_column="email",null=True)
    mobile_number = models.TextField(max_length=10,db_column="mobilenumber",null=True)
    gender = models.TextField(max_length=10,db_column="gender",null=True)
    profile_photo = models.FileField(max_length=50,db_column="profile",null=True)
    id_type = models.TextField(max_length=50,db_column="idtype",null=True)
    id_number = models.TextField(max_length=50,db_column="idnumber",null=True)
    image_of_id = models.ImageField(max_length=10,db_column="imageofid",null=True)
    second_id_type = models.TextField(max_length=50,db_column="secondidtype",null=True)
    second_id_number = models.TextField(max_length=50,db_column="secondidnumber",null=True)
    second_image_of_id = models.FileField(max_length=10,db_column="secondidimage",null=True)
    nationality = models.TextField(max_length=100,db_column="nationality",null=True)
    state = models.TextField(max_length=100,db_column="state",null=True)
    district = models.TextField(max_length=100,db_column="district",null=True)
    street_name = models.TextField(max_length=100,db_column="streetname",null=True)
    post = models.TextField(max_length=100,db_column="post",null=True)
    pin_code = models.TextField(max_length=100,db_column="pincode",null=True)
    wapp_number = models.TextField(max_length=10,db_column="wappnumber",null=True)
    licence = models.FileField(max_length=50,db_column="licence",null=True)
    available_place = models.TextField(max_length=100,db_column="availableplace",null=True)
    available_time= models.TextField(max_length=200,db_column="availabletime",null=True)
    rc = models.FileField(max_length=50,db_column="rc",null=True)
    vehicle_model = models.TextField(max_length=150,db_column="vehiclemodel",null=True)
    username = models.TextField(max_length=150,db_column="username",null=True)
    confirm_username = models.TextField(max_length=10,db_column="cusername",null=True)
    password = models.TextField(max_length=150,db_column="password",null=True)
    confirm_password = models.TextField(max_length=10,db_column="cpassword",null=True)
    status = models.TextField(max_length=10,db_column='status',null=True)
    class Meta:
        db_table='driverregistration'            